-- schema.sql — PostgreSQL + PostGIS schema.
--
-- TO IMPLEMENT HERE:
--   villages(village_id, name, district, geom GEOMETRY(Polygon,4326), population)
--   shelters(shelter_id, name, lat, lon, capacity, contact)
--   locations_features(village_id, date, precip_24h, precip_48h, precip_72h,
--                      soil_moisture, slope_deg, elevation_m, land_cover_type,
--                      pop_density, prev_slide_dist_km, forecast_precip_24h, label)
--   predictions(village_id, date, risk_score, risk_label, PRIMARY KEY(village_id, date))
--   alerts(alert_id, village_id, date, approved BOOLEAN DEFAULT FALSE,
--          approved_by, approved_at, rejection_reason)
--   citizens(citizen_id, name_enc, phone_enc, village_id, members, consent_location)
--   citizen_status(citizen_id, alert_id, status, lat, lon, reported_at)
--   users(user_id, officer_id, password_hash, is_authority, district)
--   audit_log(log_id, user_id, action, target, at)
--
-- Add a spatial index on villages.geom and a composite index on predictions(date, risk_score DESC).
